bot:
  token: BOT_TOKEN
  autopost:
    chatid: CHAT_ID
    jobs:
      rss_fhi:
        enabled: True
        interval: 5
      stats:
        enabled: True
        interval: 360
      graph_tested:
        enabled: True
        interval: 1440
      graph_confirmed:
        enabled: True
        interval: 1440
      graph_dead:
        enabled: True
        interval: 1440
      graph_hospitalized:
        enabled: True
        interval: 1440
      confirmed:
        enabled: True
        interval: 15
        text_pos_singular: ny person smittet
        text_pos_plural: nye personer smittet
        text_neg_singular: ny person friskmeldt
        text_neg_plural: nye personer friskmeldt
      dead:
        enabled: True
        interval: 5
        text_pos_singular: nytt dødsfall registrert
        text_pos_plural: nye dødsfall registrert
        text_neg_singular: dødsfall fjernet fra registeret
        text_neg_plural: dødsfall fjernet fra registeret
      hospitalized:
        enabled: True
        interval: 60
        text_pos_singular: ny person innlagt på sykehus
        text_pos_plural: nye personer innlagt på sykehus
        text_neg_singular: person skrevet ut av sykehus
        text_neg_plural: personer skrevet ut av sykehus
      intensiveCare:
        enabled: True
        interval: 60
        text_pos_singular: ny person innlagt på intensivenhet
        text_pos_plural: nye personer innlagt på intensivenhet
        text_neg_singular: person skrevet ut av intensivenhet
        text_neg_plural: personer skrevet ut av intensivenhet
      respiratory:
        enabled: True
        interval: 60
        text_pos_singular: ny person tilkoblet respirator
        text_pos_plural: nye personer tilkoblet respirator
        text_neg_singular: person frakoblet respirator
        text_neg_plural: personer frakoblet respirator
      quarantineEmployees:
        enabled: True
        interval: 60
        text_pos_singular: helsepersonell satt i karantene
        text_pos_plural: helsepersonell satt i karantene
        text_neg_singular: helsepersonell tatt ut av karantene
        text_neg_plural: helsepersonell tatt ut av karantene
      infectedEmployees:
        enabled: True
        interval: 60
        text_pos_singular: ny helsearbeider smittet
        text_pos_plural: nye helsearbeidere smittet
        text_neg_singular: helsearbeider friskmeldt
        text_neg_plural: helsearbeidere friskmeldt
  commands:
    title: "Commands"
    stats: "/stats - COVID-19 statistikk Norge (Kilde: VG)"
    tested: "/tested - Graf over testede i Norge (Kilde: VG)"
    confirmed: "/confirmed - Graf over smittede i Norge (Kilde: VG)"
    dead: "/dead - Graf over dødsfall i Norge (Kilde: VG)"
    hospitalized: "/hospitalized - Graf over sykehusinnleggelser i Norge (Kilde: VG)"
    n confirmed: "/n confirmed - Graf over antall smittede per 100k innb. i Norge, Sverige, Danmark (Kilde: VG)"
    n dead: "/n dead - Graf over antall døde per 100k innb. i Norge, Sverige, Danmark (Kilde: VG)"