version: '3.4'

services:
  bot:
    container_name: covid19norge-telegram-bot
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./config:/app/bot/config
      - ./data:/app/bot/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro