bot:
  token: BOT_TOKEN
  autopost:
    chatid: CHAT_ID
    jobs:
      rss_fhi:
        enabled: True
        interval: 5
      rss_regjeringen:
        enabled: True
        interval: 5
      tested:
          enabled: True
          interval: 5
          text_pos_singular: ny registrert testet
          text_pos_plural: nye registrert testet
          source:
            name: FHI
            url:  https://www.fhi.no/sv/smittsomme-sykdommer/corona/dags--og-ukerapporter/dags--og-ukerapporter-om-koronavirus/
      confirmed:
        enabled: True
        interval: 5
        text_pos_singular: nytt registrert smittetilfelle
        text_pos_plural: nye registrerte smittetilfeller
        text_neg_singular: 
        text_neg_plural: 
        source:
          name: MSIS
          url: https://statistikk.fhi.no/msis
      dead:
        enabled: True
        interval: 5
        text_pos_singular: nytt dødsfall registrert
        text_pos_plural: nye dødsfall registrert
        text_neg_singular: 
        text_neg_plural: 
        source:
          name: FHI
          url: https://www.fhi.no/sv/smittsomme-sykdommer/corona/dags--og-ukerapporter/dags--og-ukerapporter-om-koronavirus/
      admissions:
        enabled: True
        interval: 5
        text_pos_singular: person mer på sykehus
        text_pos_plural: flere personer på sykehus
        text_neg_singular: person mindre på sykehus
        text_neg_plural: personer færre på sykehus
        source:
          name: Helsedirektoratet
          url: https://www.helsedirektoratet.no/statistikk/antall-innlagte-pasienter-pa-sykehus-med-pavist-covid-19
      respiratory:
        enabled: True
        interval: 5
        text_pos_singular: person mer på respirator
        text_pos_plural: flere personer respirator
        text_neg_singular: person mindre på respirator
        text_neg_plural: personer færre på respirator
        source:
          name: Helsedirektoratet
          url: https://www.helsedirektoratet.no/statistikk/antall-innlagte-pasienter-pa-sykehus-med-pavist-covid-19
  commands:
    title: "Commands"
    stats: "/stats - COVID-19 statistikk Norge"
    tested: "/tested - Graf over testede i Norge"
    confirmed: "/confirmed - Graf over smittede i Norge"
    dead: "/dead - Graf over dødsfall i Norge"
    hospitalized: "/hospitalized - Graf over sykehusinnleggelser i Norge"
